name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v